name: batch-norm-only
channels:
  - pytorch
  - anaconda
  - conda-forge
dependencies:
  - cudatoolkit
  - ipykernel
  - jupyter
  - numpy
  - pip
  - python
  - pytorch
  - gensim
  - pandas
  - scikit-learn
  - matplotlib
  - pip:
    - tensorboard
    - pytorch-lightning
    - wandb
  - torchvision
  - pillow
  - tqdm
